// apps/web/app/components/company/Card.vue
<script setup lang="ts">
interface Props {
  company: Company
}

const props = defineProps<Props>()
</script>

<template>
  <KunCard
    is-pressable
    :href="`/company/${props.company.id}`"
    class-name="w-full"
  >
    <div class="flex flex-wrap items-center justify-between gap-2">
      <h2
        class="hover:text-primary-500 text-lg font-semibold transition-colors line-clamp-2"
      >
        {{ props.company.name }}
      </h2>
      <KunBadge size="sm" variant="flat">
        {{ props.company.count }} 个补丁
      </KunBadge>
    </div>
    <div
      v-if="props.company.alias && props.company.alias.length > 0"
      class="mt-2 flex flex-wrap gap-1"
    >
      <KunBadge
        v-for="alias in props.company.alias"
        :key="alias"
        size="sm"
        variant="flat"
        color="secondary"
      >
        {{ alias }}
      </KunBadge>
    </div>
  </KunCard>
</template>

// components/company/Card.tsx
import Link from 'next/link'
import { Card, CardBody } from "@heroui/card"
import { Chip } from "@heroui/chip"
import type { Company as CompanyType } from '~/types/api/company'

interface Props {
  company: CompanyType
}

export const CompanyCard = ({ company }: Props) => {
  return (
    <Card
      isPressable
      as={Link}
      href={`/company/${company.id}`}
      className="w-full"
    >
      <CardBody className="gap-2">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <h2 className="text-lg font-semibold transition-colors line-clamp-2 hover:text-primary-500">
            {company.name}
          </h2>
          <Chip size="sm" variant="flat">
            {company.count} 个补丁
          </Chip>
        </div>
        {company.alias.length > 0 && (
          <div className="flex flex-wrap gap-1 mt-2">
            {company.alias.map((alias, index) => (
              <Chip key={index} size="sm" variant="flat" color="secondary">
                {alias}
              </Chip>
            ))}
          </div>
        )}
      </CardBody>
    </Card>
  )
}
