// apps/web/app/components/comment/Card.vue
<script setup lang="ts">
interface Props {
  comment: PatchComment
}

const props = defineProps<Props>()

const patchName = computed(() =>
  getPreferredLanguageText(props.comment.patchName)
)
</script>

<template>
  <KunCard
    is-pressable
    :href="`/patch/${props.comment.patchId}/comment`"
    class-name="w-full"
  >
    <div class="flex gap-4">
      <KunAvatar :user="props.comment.user" />
      <div class="space-y-2">
        <div class="flex flex-wrap items-center gap-2">
          <h2 class="font-semibold">{{ props.comment.user.name }}</h2>
          <span class="text-small text-default-500">
            评论在
            <span class="text-primary-500">{{ patchName }}</span>
          </span>
        </div>
        <p class="mt-1">{{ props.comment.content }}</p>
        <div class="mt-2 flex items-center gap-4">
          <div class="text-small text-default-500 flex items-center gap-1">
            <KunIcon name="lucide:thumbs-up" class="size-3.5" />
            {{ props.comment.like }}
          </div>
          <span class="text-small text-default-500">
            {{
              formatDate(props.comment.created, {
                isPrecise: true,
                isShowYear: true
              })
            }}
          </span>
        </div>
      </div>
    </div>
  </KunCard>
</template>

// components/admin/log/Card.tsx
import { Avatar } from '@nextui-org/avatar'
import { Card, CardBody } from '@nextui-org/card'
import { Chip } from '@nextui-org/chip'
import { formatDate } from '~/utils/time'
import { ADMIN_LOG_TYPE_MAP } from '~/constants/admin'
import type { AdminLog } from '~/types/api/admin'

interface Props {
  log: AdminLog
}

export const LogCard = ({ log }: Props) => {
  return (
    <Card>
      <CardBody>
        <div className="flex gap-4">
          <Avatar
            src={log.user.avatar}
            alt={log.user.name}
            className="shrink-0"
          />
          <div className="w-full">
            <pre>{log.content}</pre>

            <div className="flex items-center gap-4 mt-2">
              <span className="text-small text-default-500">
                {formatDate(log.created, {
                  isPrecise: true,
                  isShowYear: true
                })}
              </span>

              <Chip color="primary" variant="flat" size="sm">
                {ADMIN_LOG_TYPE_MAP[log.type]}
              </Chip>
            </div>
          </div>
        </div>
      </CardBody>
    </Card>
  )
}
