// apps/web/app/components/release/Card.vue
<script setup lang="ts">
interface Props {
  patch: GalgameReleaseCard
}

const props = defineProps<Props>()

const displayName = computed(() => getPreferredLanguageText(props.patch.name))

const bannerSrc = computed(() =>
  props.patch.banner
    ? props.patch.banner.replace(/\.avif$/, '-mini.avif')
    : '/kungalgame-trans.webp'
)
</script>

<template>
  <KunCard
    is-pressable
    :href="`/patch/${props.patch.patchId}/introduction`"
    class-name="border-default-100 dark:border-default-200 h-full w-full border"
    content-class="p-0 gap-0"
  >
    <div
      class="relative mx-auto w-full overflow-hidden rounded-t-lg text-center opacity-90"
    >
      <KunImage
        :alt="displayName"
        :src="bannerSrc"
        class-name="size-full object-cover"
        style="aspect-ratio: 16 / 9"
      />
    </div>
    <div class="justify-between space-y-2 p-3">
      <h2
        class="hover:text-primary-500 text-medium line-clamp-2 font-semibold transition-colors sm:text-lg"
      >
        {{ displayName }}
      </h2>

      <div class="flex items-center justify-between gap-2">
        <KunBadge size="sm" color="primary" variant="flat">
          发售于 {{ formatDate(props.patch.released) }}
        </KunBadge>

        <div class="flex items-center gap-1">
          <KunIcon name="lucide:puzzle" class="text-default-500 size-4" />
          <span class="text-default-500 text-sm">
            {{ props.patch.resourceCount }}
          </span>
        </div>
      </div>
    </div>
  </KunCard>
</template>

// components/user/galgame/Card.tsx
import { Chip } from '@heroui/chip'
import { Card, CardBody } from '@heroui/card'
import { Image } from '@heroui/image'
import Link from 'next/link'
import { formatDistanceToNow } from '~/utils/formatDistanceToNow'
import { KunCardStats } from '~/components/kun/CardStats'
import { SUPPORTED_TYPE_MAP } from '~/constants/resource'

interface Props {
  galgame: GalgameCard
}

export const UserGalgameCard = ({ galgame }: Props) => {
  return (
    <Card
      isPressable
      as={Link}
      href={`/patch/${galgame.id}/introduction`}
      target="_blank"
      className="w-full"
    >
      <CardBody className="p-4">
        <div className="flex flex-col gap-4 sm:flex-row">
          <div className="relative w-full sm:h-auto sm:w-40">
            <Image
              src={
                galgame.banner
                  ? galgame.banner.replace(/\.avif$/, '-mini.avif')
                  : '/kungalgame.avif'
              }
              alt={galgame.name}
              className="object-cover rounded-lg size-full max-h-52"
              radius="lg"
            />
          </div>
          <div className="flex-1 space-y-3">
            <div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-center">
              <h2 className="text-lg font-semibold transition-colors line-clamp-2 hover:text-primary-500">
                {galgame.name}
              </h2>
              <Chip variant="flat">{formatDistanceToNow(galgame.created)}</Chip>
            </div>

            <KunCardStats patch={galgame} />

            <div className="flex flex-wrap gap-2">
              {galgame.type.map((type) => (
                <Chip
                  key={type}
                  size="sm"
                  color="primary"
                  variant="flat"
                  className="text-xs"
                >
                  {SUPPORTED_TYPE_MAP[type]}
                </Chip>
              ))}
            </div>
          </div>
        </div>
      </CardBody>
    </Card>
  )
}
