// apps/web/app/components/kun/Footer.vue
<script setup lang="ts">
const currentYear = new Date().getFullYear()
</script>

<template>
  <footer class="border-default/20 mt-8 w-full border-t text-sm">
    <div class="mx-auto max-w-7xl px-4">
      <div
        class="flex flex-wrap justify-center gap-4 py-6 md:justify-between"
      >
        <NuxtLink to="/" class="flex items-center space-x-2">
          <KunImage
            src="/favicon.webp"
            alt="鲲 Galgame 补丁"
            :width="30"
            :height="30"
            class-name="rounded-full"
          />
          <span>© {{ currentYear }} 鲲 Galgame 补丁</span>
        </NuxtLink>

        <div class="flex space-x-8">
          <NuxtLink to="/about" class="flex items-center">使用指南</NuxtLink>
          <a
            href="https://nav.kungal.org"
            target="_blank"
            rel="noopener noreferrer"
            class="flex items-center"
          >
            网站集群
          </a>
          <NuxtLink to="/friend-link" class="flex items-center">
            友情链接
          </NuxtLink>
          <a
            href="https://github.com/KUN1007/kun-galgame-patch-next"
            target="_blank"
            rel="noopener noreferrer"
            class="flex items-center"
          >
            GitHub 仓库
          </a>
        </div>

        <div class="flex space-x-8">
          <span class="flex items-center">联系我们</span>
          <a
            href="https://t.me/kungalgame"
            target="_blank"
            rel="noopener noreferrer"
            class="flex items-center"
          >
            Telegram
          </a>
          <a href="https://www.kungal.com" class="flex items-center">
            主站论坛
          </a>
        </div>
      </div>
    </div>
  </footer>
</template>

// components/kun/Footer.tsx
'use client'

import Link from 'next/link'
import Image from 'next/image'

export const KunFooter = () => {
  return (
    <footer className="w-full mt-8 text-sm border-t border-divider">
      <div className="px-4 mx-auto max-w-7xl">
        <div className="flex flex-wrap justify-center gap-4 py-6 md:justify-between">
          <Link href="/" className="flex items-center space-x-2">
            <Image
              src="/favicon.webp"
              alt="鲲 Galgame 补丁"
              width={30}
              height={30}
              className="rounded-full"
            />
            <span>© 2024 鲲 Galgame 补丁</span>
          </Link>

          <div className="flex space-x-8">
            <Link href="/about" className="flex items-center">
              使用指南
            </Link>
            <Link
              href="https://nav.kungal.org"
              target="_blank"
              className="flex items-center"
            >
              网站集群
            </Link>

            <Link href="/friend-link" className="flex items-center">
              友情链接
            </Link>

            <Link
              href="https://github.com/KUN1007/kun-galgame-patch-next"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center"
            >
              GitHub 仓库
            </Link>
          </div>

          <div className="flex space-x-8">
            <span className="flex items-center">联系我们</span>
            <Link
              href="https://t.me/kungalgame"
              className="flex items-center"
              target="_blank"
              rel="noopener noreferrer"
            >
              Telegram
            </Link>
            <Link href="https://www.kungal.com" className="flex items-center">
              主站论坛
            </Link>
          </div>
        </div>
      </div>
    </footer>
  )
}
