// apps/web/app/components/kun/TextDivider.vue
<script setup lang="ts">
interface Props {
  text: string
}

const props = defineProps<Props>()
</script>

<template>
  <div class="flex w-full items-center justify-center overflow-hidden">
    <div class="border-default/20 my-4 w-full border-t" />
    <span class="text-default-500 mx-4 text-sm whitespace-nowrap">
      {{ props.text }}
    </span>
    <div class="border-default/20 my-4 w-full border-t" />
  </div>
</template>

// components/kun/TextDivider.tsx
import { Divider } from '@heroui/divider'

interface Props {
  text: string
}

export const KunTextDivider = ({ text }: Props) => {
  return (
    <div className="flex items-center justify-center w-full overflow-hidden">
      <Divider className="my-8" />
      <span className="mx-4 whitespace-nowrap text-default-500">{text}</span>
      <Divider className="my-8" />
    </div>
  )
}
