// components/forgot/StepOne.tsx
'use client'

import { useState } from 'react'
import { z } from 'zod'
import { Controller, useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { Button, Input } from "@heroui/react"
import { User } from 'lucide-react'
import { kunFetchPost } from '~/utils/kunFetch'
import { kunErrorHandler } from '~/utils/kunErrorHandler'
import toast from 'react-hot-toast'
import { stepOneSchema } from '~/validations/forgot'

type StepOneFormData = z.infer<typeof stepOneSchema>

interface Props {
  setStep: (step: number) => void
  setEmail: (username: string) => void
}

export const StepOne = ({ setStep, setEmail }: Props) => {
  const [loading, setLoading] = useState(false)

  const { control, watch } = useForm<StepOneFormData>({
    resolver: zodResolver(stepOneSchema),
    defaultValues: {
      name: ''
    }
  })

  const handleSendCode = async (data: StepOneFormData) => {
    setLoading(true)

    const res = await kunFetchPost<KunResponse<undefined>>('/forgot/one', {
      name: data.name
    })
    kunErrorHandler(res, () => {
      setEmail(data.name)
      setStep(2)
      toast.success('重置验证码发送成功!')
    })

    setLoading(false)
  }

  return (
    <form className="w-full space-y-4">
      <Controller
        name="name"
        control={control}
        render={({ field, formState: { errors } }) => (
          <Input
            {...field}
            label="邮箱"
            placeholder="请输入您的邮箱"
            autoComplete="email"
            isInvalid={!!errors.name}
            errorMessage={errors.name?.message}
            startContent={<User className="size-4 text-default-400" />}
          />
        )}
      />
      <Button
        color="primary"
        className="w-full"
        isLoading={loading}
        onPress={() => handleSendCode(watch())}
      >
        发送验证码
      </Button>
    </form>
  )
}

// apps/web/app/components/forgot/StepOne.vue
<script setup lang="ts">
import { stepOneSchema } from '~/shared/validations/forgot'

interface Props {
  modelStep: number
}

defineProps<Props>()

const emit = defineEmits<{
  'update:modelStep': [value: number]
  'update:email': [value: string]
}>()

const api = useApi()

const form = reactive({ name: '' })
const errors = ref<Record<string, string>>({})
const loading = ref(false)

const validate = () => {
  const result = stepOneSchema.safeParse(form)
  if (!result.success) {
    errors.value = { name: result.error.issues[0]?.message ?? '' }
    return false
  }
  errors.value = {}
  return true
}

const handleSendCode = async () => {
  if (!validate()) return
  loading.value = true
  try {
    const res = await api.post('/auth/forgot/send-code', { name: form.name })
    if (res.code === 0) {
      emit('update:email', form.name)
      emit('update:modelStep', 2)
      useKunMessage('重置验证码发送成功!', 'success')
    } else {
      useKunMessage(res.message || '发送失败', 'error')
    }
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <form class="w-full space-y-4" @submit.prevent="handleSendCode">
    <KunInput
      v-model="form.name"
      label="邮箱"
      placeholder="请输入您的邮箱"
      autocomplete="email"
      :error="errors.name"
    >
      <template #prefix>
        <KunIcon name="lucide:user" class="text-default-400 size-4" />
      </template>
    </KunInput>
    <KunButton
      type="submit"
      color="primary"
      full-width
      :loading="loading"
      :disabled="loading"
    >
      发送验证码
    </KunButton>
  </form>
</template>
