// components/apply/Success.tsx
'use client'

import { useEffect } from 'react'
import { Button, Card, CardBody } from '@heroui/react'
import { motion } from 'framer-motion'
import { BadgeCheck, Home, Rocket } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { useConfetti } from '~/hooks/useConfetti'

export const ApplySuccess = () => {
  const router = useRouter()
  const triggerConfetti = useConfetti()

  useEffect(() => {
    triggerConfetti()
  }, [triggerConfetti])

  return (
    <motion.div
      initial={{ scale: 0.9, opacity: 0 }}
      animate={{ scale: 1, opacity: 1 }}
      transition={{ duration: 0.5 }}
    >
      <Card className="mx-auto max-w-96">
        <CardBody className="flex flex-col items-center gap-6 py-8">
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ delay: 0.2, type: 'spring', stiffness: 200 }}
            className="flex items-center justify-center rounded-full size-20"
          >
            <BadgeCheck
              className="size-20 text-primary-foreground"
              fill="#006FEE"
            />
          </motion.div>

          <div className="space-y-2 text-center">
            <motion.h1
              className="text-3xl font-bold"
              initial={{ y: 20, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              transition={{ delay: 0.3 }}
            >
              恭喜成为创作者！
            </motion.h1>
            <motion.p
              className="text-default-500"
              initial={{ y: 20, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              transition={{ delay: 0.4 }}
            >
              您现在可以使用创作者专属功能了
            </motion.p>
          </div>

          <motion.div
            className="space-x-4"
            initial={{ y: 20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ delay: 0.5 }}
          >
            <Button
              startContent={<Rocket className="size-4" />}
              color="primary"
              variant="shadow"
              className="flex-1"
              size="lg"
              onPress={() => router.push('/edit/create')}
            >
              发布补丁
            </Button>
            <Button
              startContent={<Home className="size-4" />}
              variant="bordered"
              className="flex-1"
              size="lg"
              onPress={() => router.push('/')}
            >
              返回首页
            </Button>
          </motion.div>
        </CardBody>
      </Card>
    </motion.div>
  )
}

// apps/web/app/pages/apply/success.vue
<script setup lang="ts">
useKunSeoMeta({
  title: '成为创作者',
  description: '恭喜您成为创作者'
})
</script>

<template>
  <div class="m-auto w-full">
    <KunCard class-name="mx-auto max-w-96" :bordered="true">
      <div class="flex flex-col items-center gap-6 py-8">
        <div class="flex size-20 items-center justify-center rounded-full">
          <KunIcon
            name="lucide:badge-check"
            class="text-primary size-20"
          />
        </div>

        <div class="space-y-2 text-center">
          <h1 class="text-3xl font-bold">恭喜成为创作者！</h1>
          <p class="text-default-500">您现在可以使用创作者专属功能了</p>
        </div>

        <div class="flex gap-3">
          <KunButton
            color="primary"
            variant="shadow"
            size="lg"
            href="/edit/create"
          >
            <KunIcon name="lucide:rocket" class="size-4" />
            发布补丁
          </KunButton>
          <KunButton variant="bordered" color="default" size="lg" href="/">
            <KunIcon name="lucide:home" class="size-4" />
            返回首页
          </KunButton>
        </div>
      </div>
    </KunCard>
  </div>
</template>
