// components/user/resource/Card.tsx
import { Chip } from '@heroui/chip'
import { Card, CardBody } from '@heroui/card'
import { Image } from '@heroui/image'
import { formatDistanceToNow } from '~/utils/formatDistanceToNow'
import Link from 'next/link'
import { KunPatchAttribute } from '~/components/kun/PatchAttribute'
import { getPreferredLanguageText } from '~/utils/getPreferredLanguageText'
import type { UserResource as UserResourceType } from '~/types/api/user'

interface Props {
  resource: UserResourceType
}

export const UserResourceCard = ({ resource }: Props) => {
  const galgameName = getPreferredLanguageText(resource.patchName)

  return (
    <Card
      isPressable
      as={Link}
      href={`/patch/${resource.patchId}/resource`}
      target="_blank"
      className="w-full"
    >
      <CardBody className="p-4">
        <div className="flex flex-col gap-4 sm:flex-row">
          <div className="relative w-full sm:h-auto sm:w-40">
            <Image
              src={
                resource.patchBanner
                  ? resource.patchBanner.replace(/\.avif$/, '-mini.avif')
                  : '/kungalgame.avif'
              }
              alt={galgameName}
              className="object-cover rounded-lg size-full max-h-52"
              radius="lg"
            />
          </div>
          <div className="flex-1 space-y-3">
            <div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-center">
              <h2 className="text-lg font-semibold transition-colors line-clamp-2 hover:text-primary-500">
                {galgameName}
              </h2>
              <Chip variant="flat">
                {formatDistanceToNow(resource.created)}
              </Chip>
            </div>

            <KunPatchAttribute
              types={resource.type}
              languages={resource.language}
              platforms={resource.platform}
              size="sm"
            />
          </div>
        </div>
      </CardBody>
    </Card>
  )
}

// apps/web/app/components/resource/Card.vue
<script setup lang="ts">
interface Props {
  resource: PatchResource
}

const props = defineProps<Props>()

const galgameName = computed(() =>
  props.resource.patch?.name
    ? getPreferredLanguageText(props.resource.patch.name)
    : ''
)
const title = computed(
  () =>
    props.resource.name ||
    galgameName.value ||
    props.resource.note ||
    '补丁资源'
)

const userDescription = computed(() => {
  const when = formatDate(props.resource.created, {
    isShowYear: true,
    isPrecise: true
  })
  return `发布于 ${when}`
})
</script>

<template>
  <KunCard
    :href="`/resource/${props.resource.id}`"
    class-name="w-full"
    padding="sm"
  >
    <div class="flex flex-col justify-between space-y-2">
      <div class="flex">
        <KunUserChip
          :user="props.resource.user"
          :description="userDescription"
          :is-navigation="false"
        />
      </div>

      <h2
        class="hover:text-primary-500 text-lg font-semibold transition-colors line-clamp-2"
      >
        {{ title }}
      </h2>

      <p
        v-if="galgameName && galgameName !== title"
        class="text-default-500 flex items-center gap-1 text-sm"
      >
        <KunIcon name="lucide:gamepad-2" class="size-3.5 shrink-0" />
        <span class="truncate">{{ galgameName }}</span>
      </p>

      <KunPatchAttribute
        :types="props.resource.type"
        :languages="props.resource.language"
        :platforms="props.resource.platform"
        :model-name="props.resource.model_name"
        size="sm"
      />

      <div
        class="text-small text-default-500 flex items-center justify-between"
      >
        <div class="flex gap-4">
          <div class="flex items-center gap-1">
            <KunIcon name="lucide:heart" class="size-4" />
            {{ props.resource.like_count }}
          </div>
          <div class="flex items-center gap-1">
            <KunIcon name="lucide:download" class="size-4" />
            {{ props.resource.download }}
          </div>
        </div>
        <KunChip size="sm" variant="flat">
          {{ props.resource.size }}
        </KunChip>
      </div>
    </div>
  </KunCard>
</template>
