// components/galgame/Card.tsx
'use client'

import { useState } from 'react'
import { Card, CardBody, CardFooter, CardHeader } from '@heroui/card'
import { Chip } from '@heroui/chip'
import { Image } from '@heroui/image'
import { KunCardStats } from '~/components/kun/CardStats'
import Link from 'next/link'
import { KunPatchAttribute } from '~/components/kun/PatchAttribute'
import { cn } from '~/utils/cn'
import { GALGAME_AGE_LIMIT_MAP } from '~/constants/galgame'
import { formatDistanceToNow } from '~/utils/formatDistanceToNow'

interface Props {
  patch: GalgameCard
}

export const GalgameCard = ({ patch }: Props) => {
  const [imageLoaded, setImageLoaded] = useState(false)

  return (
    <Card
      isPressable
      as={Link}
      href={`/patch/${patch.id}/introduction`}
      className="w-full border border-default-100 dark:border-default-200"
    >
      <CardHeader className="p-0">
        <div className="relative w-full mx-auto overflow-hidden text-center rounded-t-lg opacity-90">
          <div
            className={cn(
              'absolute inset-0 animate-pulse bg-default-100',
              imageLoaded ? 'opacity-0' : 'opacity-90',
              'transition-opacity duration-300'
            )}
            style={{ aspectRatio: '16/9' }}
          />
          <Image
            radius="none"
            alt={patch.name}
            className={cn(
              'size-full object-cover transition-all duration-300',
              imageLoaded ? 'scale-100 opacity-90' : 'scale-105 opacity-0'
            )}
            removeWrapper={true}
            src={
              patch.banner
                ? patch.banner.replace(/\.avif$/, '-mini.avif')
                : '/kungalgame.avif'
            }
            style={{ aspectRatio: '16/9' }}
            onLoad={() => setImageLoaded(true)}
          />

          <div className="absolute z-10 rounded-full bg-background left-2 top-2">
            <Chip
              color={patch.content_limit === 'sfw' ? 'success' : 'danger'}
              variant="flat"
            >
              {GALGAME_AGE_LIMIT_MAP[patch.content_limit]}
            </Chip>
          </div>

          <div className="absolute z-10 rounded-full bg-background right-2 bottom-2">
            <Chip size="sm" variant="flat">
              {formatDistanceToNow(patch.created)}
            </Chip>
          </div>
        </div>
      </CardHeader>
      <CardBody className="justify-between space-y-2">
        <h2 className="font-semibold transition-colors text-medium sm:text-lg line-clamp-2 hover:text-primary-500">
          {patch.name}
        </h2>
        <KunCardStats patch={patch} />
      </CardBody>
      <CardFooter className="pt-0">
        <KunPatchAttribute
          types={patch.type}
          languages={patch.language}
          platforms={patch.platform}
          size="sm"
        />
      </CardFooter>
    </Card>
  )
}

// apps/web/app/components/character/Card.vue
<script setup lang="ts">
import { ROLE_LABELS } from '~/constants/character'

interface Props {
  character: PatchCharacter
}

const props = defineProps<Props>()

const displayName = computed(() =>
  getPreferredLanguageText(props.character.name)
)
</script>

<template>
  <NuxtLink
    :to="`/character/${props.character.id}`"
    class="relative block overflow-hidden rounded-lg shadow-sm"
  >
    <div class="bg-default-100 aspect-[3/4] overflow-hidden">
      <KunImage
        :src="props.character.image || '/kungalgame.webp'"
        :alt="displayName"
        :class="
          cn(
            'h-full w-full object-cover object-[50%_top] dark:opacity-70',
            !props.character.image && 'opacity-30!'
          )
        "
      />
    </div>
    <div
      class="bg-background/60 absolute right-1 bottom-1 left-1 z-10 flex items-center justify-between rounded-lg border border-white/20 px-2 py-1 overflow-hidden"
    >
      <h3 class="text-sm font-bold truncate">{{ displayName }}</h3>
      <KunBadge v-if="props.character.role" size="sm" color="secondary" variant="flat">
        {{ ROLE_LABELS[props.character.role] ?? props.character.role }}
      </KunBadge>
    </div>
  </NuxtLink>
</template>
