// apps/web/app/components/edit/create/BannerImage.vue
<script setup lang="ts">
interface Props {
  errors?: string
}

defineProps<Props>()

const previewUrl = ref<string>('')

onMounted(async () => {
  const saved = await getImage('kun-patch-banner')
  if (saved) {
    previewUrl.value = URL.createObjectURL(saved)
  }
})

onUnmounted(() => {
  if (previewUrl.value) URL.revokeObjectURL(previewUrl.value)
})

const handleCropComplete = async (blob: Blob) => {
  await saveImage(blob, 'kun-patch-banner')
}

const handleRemove = async () => {
  await deleteImage('kun-patch-banner')
}
</script>

<template>
  <div class="space-y-2">
    <h2 class="text-xl">预览图片</h2>
    <p>
      注意, <b>您不可以使用 R18 图片作为封面</b>, 如果有, 请更换图片、打码或裁剪
    </p>
    <p>
      预览图片实在太影响排版了, 无论如何请尽量寻找一个清晰的图片
    </p>
    <p v-if="errors" class="text-danger-500 text-xs">{{ errors }}</p>

    <KunCropperImageCropper
      :aspect-ratio="16 / 9"
      :initial-image="previewUrl"
      hint="点击或拖放图片到此处裁剪"
      description="您的预览图片将会被固定为 16:9 比例"
      @complete="handleCropComplete"
      @remove="handleRemove"
    />
  </div>
</template>

// components/edit/create/BannerImage.tsx
'use client'

import { useEffect, useState } from 'react'
import localforage from 'localforage'
import { dataURItoBlob } from '~/utils/dataURItoBlob'
// import { resizeImage } from '~/utils/resizeImage'
import { KunImageCropper } from '~/components/kun/cropper/KunImageCropper'

interface Props {
  errors: string | undefined
}

export const BannerImage = ({ errors }: Props) => {
  const [initialUrl, setInitialUrl] = useState<string>('')

  useEffect(() => {
    const fetchData = async () => {
      const localeBannerBlob: Blob | null =
        await localforage.getItem('kun-patch-banner')
      if (localeBannerBlob) {
        setInitialUrl(URL.createObjectURL(localeBannerBlob))
      }
    }
    fetchData()
  }, [])

  const removeBanner = async () => {
    await localforage.removeItem('kun-patch-banner')
    setInitialUrl('')
  }

  const onImageComplete = async (croppedImage: string) => {
    const imageBlob = dataURItoBlob(croppedImage)
    // const imageFile = new File([imageBlob], 'banner.webp', {
    //   type: imageBlob.type
    // })
    // const miniImage = await resizeImage(imageFile, 1920, 1080)
    await localforage.setItem('kun-patch-banner', imageBlob)
  }

  return (
    <div className="space-y-2">
      <h2 className="text-xl">预览图片</h2>
      <p>
        注意, <b>您不可以使用 R18 图片作为封面</b>, 如果有, 请更换图片, 打码,
        或者裁剪
      </p>
      <p>
        预览图片实在太影响排版了, 无论如何请尽量寻找一个清晰的图片, 可以直接前往
        E-Hentai (E 站) 获取
      </p>
      {errors && <p className="text-xs text-danger-500">{errors}</p>}

      <KunImageCropper
        aspect={{ x: 16, y: 9 }}
        initialImage={initialUrl}
        description="您的预览图片将会被固定为 1920 × 1080 分辨率"
        onImageComplete={onImageComplete}
        removeImage={removeBanner}
      />
    </div>
  )
}
