// apps/web/app/components/home/carousel/DesktopCard.vue
<script setup lang="ts">
import { aboutDirectoryLabelMap } from '~/constants/about'

interface Props {
  posts: HomeCarouselMetadata[]
  currentSlide: number
}

const props = defineProps<Props>()

const post = computed(() => props.posts[props.currentSlide])
</script>

<template>
  <div v-if="post" class="group hidden h-full sm:block">
    <img
      :alt="post.title"
      class="h-full w-full rounded-2xl object-cover brightness-75"
      :src="post.banner"
    />
    <div
      class="absolute inset-0 rounded-2xl bg-gradient-to-t from-black/30 via-black/10 to-transparent"
    />

    <HomeCarouselNavigationMenu />

    <div
      class="bg-background/80 absolute right-4 bottom-4 left-4 rounded-lg border-none p-4 backdrop-blur-md"
    >
      <div class="flex justify-between">
        <div>
          <div class="mb-2 flex items-center gap-3">
            <img
              :src="post.authorAvatar"
              :alt="post.authorName"
              class="h-6 w-6 rounded-full"
            />
            <span class="text-foreground/80 text-sm">
              {{ post.authorName }}
            </span>
          </div>
          <KunLink
            color="default"
            underline="none"
            :to="post.link"
            class-name="hover:text-primary-500 mb-2 text-2xl font-bold line-clamp-1"
          >
            <h1>{{ post.title }}</h1>
          </KunLink>
        </div>
      </div>

      <p class="text-foreground/80 mb-2 text-sm line-clamp-1">
        {{ post.description }}
      </p>
      <div class="flex flex-wrap gap-2">
        <KunBadge variant="flat" size="sm" color="primary">
          {{ aboutDirectoryLabelMap[post.directory] }}
        </KunBadge>

        <KunBadge variant="flat" size="sm">
          {{ formatDistanceToNow(post.date) }}
        </KunBadge>
      </div>
    </div>
  </div>
</template>

// components/home/carousel/DesktopCard.tsx
'use client'

import { Card, Chip, Link } from '@heroui/react'
import { aboutDirectoryLabelMap } from '~/constants/about'
import { KunNavigationMenu } from './KunNavigationMenu'
import { formatDistanceToNow } from '~/utils/formatDistanceToNow'
import type { HomeCarouselMetadata } from './mdx'

interface Props {
  posts: HomeCarouselMetadata[]
  currentSlide: number
}

export const KunDesktopCard = ({ posts, currentSlide }: Props) => {
  const post = posts[currentSlide]

  return (
    <div className="hidden h-full sm:block group">
      <img
        alt={post.title}
        className="object-cover w-full h-full brightness-75 rounded-2xl"
        src={post.banner}
      />
      <div className="absolute inset-0 rounded-2xl bg-gradient-to-t from-black/30 via-black/10 to-transparent" />

      <KunNavigationMenu />

      <Card className="absolute border-none bottom-4 left-4 right-4 bg-background/80 backdrop-blur-md">
        <div className="p-4">
          <div className="flex justify-between">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <img
                  src={post.authorAvatar}
                  alt={post.authorName}
                  className="w-6 h-6 rounded-full"
                />
                <span className="text-sm text-foreground/80">
                  {post.authorName}
                </span>
              </div>
              <Link
                color="foreground"
                className="mb-2 text-2xl font-bold hover:text-primary-500 line-clamp-1"
                href={post.link}
              >
                <h1>{post.title}</h1>
              </Link>
            </div>
          </div>

          <p className="mb-2 text-sm text-foreground/80 line-clamp-1">
            {post.description}
          </p>
          <div className="flex flex-wrap gap-2">
            <Chip variant="flat" size="sm" color="primary">
              {aboutDirectoryLabelMap[post.directory]}
            </Chip>

            <Chip variant="flat" size="sm">
              {formatDistanceToNow(post.date)}
            </Chip>
          </div>
        </div>
      </Card>
    </div>
  )
}
