// components/person/Card.tsx
import { Card, CardBody } from '@heroui/card'
import { Image, Chip } from '@heroui/react'
import NextLink from 'next/link'
import type { Person } from '~/types/api/person'

export const PersonCard = ({ person }: { person: Person }) => (
  <Card className="shadow-sm overflow-hidden">
    <div className="aspect-[3/3] overflow-hidden bg-default-100">
      <Image
        src={person.image || '/person.avif'}
        alt={person.name_zh_cn || person.name_ja_jp}
        className="w-full h-full object-cover"
      />
    </div>
    <CardBody className="p-3">
      <h3 className="font-bold text-sm truncate">
        <NextLink href={`/person/${person.id}`} className="hover:underline">
          {person.name_zh_cn || person.name_ja_jp || person.name_en_us}
        </NextLink>
      </h3>
      <div className="flex flex-wrap gap-2 mt-2">
        {person.roles.slice(0, 3).map((r) => (
          <Chip key={r} size="sm" variant="flat">
            {r}
          </Chip>
        ))}
      </div>
    </CardBody>
  </Card>
)

// apps/web/app/components/person/Card.vue
<script setup lang="ts">
import { roleLabel } from '~/constants/character'

interface Props {
  person: PatchPerson
}

const props = defineProps<Props>()

const displayName = computed(() => getPreferredLanguageText(props.person.name))
</script>

<template>
  <div class="flex gap-3">
    <div
      class="bg-default-100 flex size-12 shrink-0 items-center justify-center overflow-hidden rounded-xl sm:size-16"
    >
      <KunImage
        :src="props.person.image || '/kungalgame.webp'"
        :alt="displayName"
        class-name="h-full w-full object-cover"
      />
    </div>

    <div>
      <h3 class="font-semibold truncate">
        <NuxtLink
          :to="`/person/${props.person.id}`"
          class="hover:text-primary-500"
        >
          {{ displayName }}
        </NuxtLink>
      </h3>

      <div class="flex flex-wrap gap-2">
        <span
          v-for="r in props.person.roles.slice(0, 3)"
          :key="r"
          class="text-default-500 text-sm"
        >
          {{ roleLabel(r) }}
        </span>
      </div>
    </div>
  </div>
</template>
