// apps/next-web/app/auth/callback/page.tsx
'use client'

import { useEffect, useRef, useState } from 'react'
import { useRouter } from '@bprogress/next'
import { Card, CardBody, Spinner } from '@heroui/react'
import { kunFetchPost } from '~/utils/kunFetch'
import { verifyOAuthCallback } from '~/utils/pkce'
import { useUserStore } from '~/store/userStore'
import toast from 'react-hot-toast'
import type { UserState } from '~/store/userStore'

export default function OAuthCallbackPage() {
  const router = useRouter()
  const { setUser } = useUserStore()
  const [error, setError] = useState<string | null>(null)
  const processed = useRef(false)

  useEffect(() => {
    if (processed.current) {
      return
    }
    processed.current = true

    const handleCallback = async () => {
      const params = verifyOAuthCallback()
      if (!params) {
        setError('OAuth callback verification failed')
        setTimeout(() => router.push('/login'), 2000)
        return
      }

      const res = await kunFetchPost<KunResponse<UserState>>(
        '/auth/oauth/callback',
        {
          code: params.code,
          code_verifier: params.codeVerifier
        }
      )

      if (typeof res === 'string') {
        setError(res)
        toast.error(res)
        setTimeout(() => router.push('/login'), 2000)
        return
      }

      setUser(res)
      toast.success('登录成功!')
      router.push(`/user/${res.uid}/resource`)
    }

    handleCallback()
  }, [])

  return (
    <div className="flex items-center justify-center min-h-[50vh]">
      <Card className="w-full max-w-sm">
        <CardBody className="flex flex-col items-center gap-4 py-8">
          {error ? (
            <>
              <p className="text-danger text-center">{error}</p>
              <p className="text-sm text-default-400">
                Redirecting to login...
              </p>
            </>
          ) : (
            <>
              <Spinner size="lg" />
              <p className="text-default-500">正在完成登录...</p>
            </>
          )}
        </CardBody>
      </Card>
    </div>
  )
}

// apps/web/app/pages/auth/callback.vue
<script setup lang="ts">
import type { UserState } from '~/stores/userStore'

useKunSeoMeta({
  title: 'OAuth 回调',
  description: '正在完成 OAuth 登录'
})

definePageMeta({
  ssr: false
})

const api = useApi()
const userStore = useUserStore()

const error = ref<string | null>(null)
const processed = ref(false)

onMounted(async () => {
  if (processed.value) return
  processed.value = true

  const params = verifyOAuthCallback()
  if (!params) {
    error.value = 'OAuth callback verification failed'
    setTimeout(() => navigateTo('/login'), 2000)
    return
  }

  const res = await api.post<UserState>('/auth/oauth/callback', {
    code: params.code,
    code_verifier: params.codeVerifier
  })

  if (res.code !== 0) {
    error.value = res.message
    useKunMessage(res.message || '登录失败', 'error')
    setTimeout(() => navigateTo('/login'), 2000)
    return
  }

  userStore.setUser(res.data)
  useKunMessage('登录成功!', 'success')
  await navigateTo(`/user/${res.data.uid}/resource`)
})
</script>

<template>
  <div class="flex min-h-[50vh] items-center justify-center">
    <KunCard class-name="w-full max-w-sm" :bordered="false">
      <div class="flex flex-col items-center gap-4 py-8">
        <template v-if="error">
          <p class="text-danger text-center">{{ error }}</p>
          <p class="text-default-400 text-sm">Redirecting to login...</p>
        </template>
        <template v-else>
          <KunIcon
            name="svg-spinners:90-ring-with-bg"
            class="text-primary size-10"
          />
          <p class="text-default-500">正在完成登录...</p>
        </template>
      </div>
    </KunCard>
  </div>
</template>
