// apps/web/app/components/kun/top-bar/User.vue
<script setup lang="ts">
import type { UserState } from '~/stores/userStore'

const userStore = useUserStore()
const api = useApi()

const unreadMessageTypes = ref<string[]>([])
const mounted = ref(false)

const fetchUserStatus = async () => {
  const res = await api.get<UserState>('/auth/me')
  if (res.code === 0) {
    userStore.setUser({
      ...res.data,
      mutedMessageTypes: userStore.user.mutedMessageTypes ?? []
    })
  } else {
    userStore.logout()
  }
}

const fetchUnread = async () => {
  const res = await api.get<string[]>('/message/unread')
  if (res.code === 0) {
    unreadMessageTypes.value = res.data ?? []
  }
}

onMounted(async () => {
  mounted.value = true
  if (userStore.user.uid) {
    await Promise.all([fetchUserStatus(), fetchUnread()])
  }
})
</script>

<template>
  <div class="ml-auto flex items-center gap-2">
    <template v-if="mounted">
      <template v-if="!userStore.user.name">
        <KunButton size="sm" color="primary" variant="flat" href="/login">
          登录
        </KunButton>
        <KunButton
          size="sm"
          color="primary"
          href="/register"
          class-name="hidden lg:inline-flex"
        >
          注册
        </KunButton>
      </template>

      <KunTopBarNSFWSwitcher />

      <KunTopBarSearch />

      <div class="hidden sm:flex">
        <KunTopBarRandomGalgameButton
          is-icon-only
          variant="light"
          size="sm"
        />
      </div>

      <div class="hidden sm:flex">
        <KunTopBarThemeSwitcher />
      </div>

      <template v-if="userStore.user.name">
        <KunTopBarUserMessageBell
          :unread-message-types="unreadMessageTypes"
          @read-messages="unreadMessageTypes = []"
        />
        <KunTopBarUserDropdown />
      </template>
    </template>

    <template v-else>
      <div class="bg-default-100 h-10 w-32 animate-pulse rounded-lg" />
    </template>
  </div>
</template>

// apps/web/components/kun/top-bar/User.tsx
'use client'

import toast from 'react-hot-toast'
import { useEffect, useState } from 'react'
import { NavbarContent, NavbarItem } from '@heroui/navbar'
import Link from 'next/link'
import { Button } from '@heroui/button'
import { Skeleton } from '@heroui/skeleton'
import { useUserStore } from '~/store/userStore'
import { useRouter } from 'next/navigation'
import { kunFetchGet } from '~/utils/kunFetch'
import { ThemeSwitcher } from './ThemeSwitcher'
import { useMounted } from '~/hooks/useMounted'
import { UserDropdown } from './UserDropdown'
import { KunSearch } from './Search'
import { UserMessageBell } from './UserMessageBell'
import { NSFWSwitcher } from './NSFWSwitcher'
import { kunErrorHandler } from '~/utils/kunErrorHandler'
import { RandomGalgameButton } from './RandomGalgameButton'
import { Tooltip } from '@heroui/react'
import type { UserState } from '~/store/userStore'

export const KunTopBarUser = () => {
  const router = useRouter()
  const { user, setUser, logout } = useUserStore()
  const [unreadMessageTypes, setUnreadMessageTypes] = useState<string[]>([])
  const isMounted = useMounted()

  const getUserStatus = async () => {
    const res = await kunFetchGet<KunResponse<UserState>>('/auth/me')
    if (typeof res === 'string') {
      logout()
      return
    }
    setUser({ ...res, mutedMessageTypes: user.mutedMessageTypes ?? [] })
  }

  const getUserUnreadMessage = async () => {
    const response = await kunFetchGet<KunResponse<string[]>>('/message/unread')
    kunErrorHandler(response, (value) => {
      setUnreadMessageTypes(value)
    })
  }

  useEffect(() => {
    if (!isMounted) {
      return
    }
    if (!user.uid) {
      return
    }
    getUserStatus()
    getUserUnreadMessage()
  }, [isMounted])

  return (
    <NavbarContent as="div" className="items-center" justify="end">
      {isMounted ? (
        <>
          {!user.name && (
            <NavbarContent justify="end">
              <NavbarItem>
                <Button
                  size="sm"
                  color="primary"
                  variant="flat"
                  as={Link}
                  href="/login"
                >
                  登录
                </Button>
              </NavbarItem>
              <NavbarItem className="hidden lg:flex">
                <Button size="sm" as={Link} color="primary" href="/register">
                  注册
                </Button>
              </NavbarItem>
            </NavbarContent>
          )}

          <NSFWSwitcher />

          <KunSearch />

          <Tooltip disableAnimation content="随机一部游戏">
            <RandomGalgameButton
              className="hidden sm:flex"
              isIconOnly
              variant="light"
              size="sm"
            />
          </Tooltip>

          <div className="hidden sm:flex">
            <ThemeSwitcher />
          </div>

          {user.name && (
            <>
              <UserMessageBell
                unreadMessageTypes={unreadMessageTypes}
                readMessages={() => setUnreadMessageTypes([])}
              />

              <UserDropdown />
            </>
          )}
        </>
      ) : (
        <Skeleton className="rounded-lg">
          <div className="w-32 h-10 rounded-lg bg-default-300" />
        </Skeleton>
      )}
    </NavbarContent>
  )
}
