// apps/web/app/components/kun/PatchAttribute.vue
<script setup lang="ts">
import {
  SUPPORTED_LANGUAGE_MAP,
  SUPPORTED_PLATFORM_MAP,
  SUPPORTED_TYPE_MAP,
  SUPPORTED_RESOURCE_LINK_MAP
} from '~/constants/resource'
import type { KunUISize } from './ui/type'

interface Props {
  types: string[]
  languages: string[]
  platforms: string[]
  modelName?: string
  downloadCount?: number
  storage?: string
  storageSize?: string
  className?: string
  size?: KunUISize
}

const props = withDefaults(defineProps<Props>(), {
  modelName: '',
  downloadCount: undefined,
  storage: '',
  storageSize: '',
  className: '',
  size: 'md'
})
</script>

<template>
  <div :class="cn('flex flex-wrap gap-2', props.className)">
    <KunBadge
      v-for="type in props.types"
      :key="type"
      variant="flat"
      color="primary"
      :size="props.size"
    >
      {{ SUPPORTED_TYPE_MAP[type] }}
    </KunBadge>

    <KunBadge
      v-for="lang in props.languages"
      :key="lang"
      variant="flat"
      color="secondary"
      :size="props.size"
    >
      {{ SUPPORTED_LANGUAGE_MAP[lang] }}
    </KunBadge>

    <KunBadge
      v-for="platform in props.platforms"
      :key="platform"
      variant="flat"
      color="success"
      :size="props.size"
    >
      {{ SUPPORTED_PLATFORM_MAP[platform] }}
    </KunBadge>

    <KunBadge
      v-if="props.modelName"
      variant="flat"
      color="danger"
      :size="props.size"
    >
      {{ props.modelName }}
    </KunBadge>

    <KunBadge v-if="props.storage" variant="flat" color="secondary">
      <KunIcon
        v-if="props.storage === 's3'"
        name="lucide:cloud"
        class="size-4"
      />
      <KunIcon
        v-else-if="props.storage === 'user'"
        name="lucide:link"
        class="size-4"
      />
      {{ SUPPORTED_RESOURCE_LINK_MAP[props.storage] }}
    </KunBadge>

    <KunBadge v-if="props.storageSize" variant="flat" color="warning">
      <KunIcon name="lucide:database" class="size-4" />
      {{ props.storageSize }}
    </KunBadge>

    <KunBadge
      v-if="props.downloadCount"
      variant="flat"
      color="default"
      :size="props.size"
    >
      {{ `${props.downloadCount} 人下载` }}
    </KunBadge>
  </div>
</template>

// apps/web/components/kun/PatchAttribute.tsx
import { Chip } from '@heroui/chip'
import { Cloud, Link as LinkIcon, Database } from 'lucide-react'
import {
  SUPPORTED_LANGUAGE_MAP,
  SUPPORTED_PLATFORM_MAP,
  SUPPORTED_TYPE_MAP,
  SUPPORTED_RESOURCE_LINK_MAP
} from '~/constants/resource'
import { cn } from '~/utils/cn'
import type { JSX } from 'react'

interface Props {
  types: string[]
  languages: string[]
  platforms: string[]
  modelName?: string
  downloadCount?: number
  storage?: string
  storageSize?: string
  className?: string
  size?: 'lg' | 'md' | 'sm'
}

const storageIcons: { [key: string]: JSX.Element } = {
  s3: <Cloud className="size-4" />,
  user: <LinkIcon className="size-4" />
}

export const KunPatchAttribute = ({
  types,
  languages,
  platforms,
  modelName = '',
  downloadCount,
  storage = '',
  storageSize = '',
  className = '',
  size = 'md'
}: Props) => {
  return (
    <div className={cn('flex flex-wrap gap-2', className)}>
      {types.map((type) => (
        <Chip key={type} variant="flat" color="primary" size={size}>
          {SUPPORTED_TYPE_MAP[type]}
        </Chip>
      ))}
      {languages.map((lang) => (
        <Chip key={lang} variant="flat" color="secondary" size={size}>
          {SUPPORTED_LANGUAGE_MAP[lang]}
        </Chip>
      ))}
      {platforms.map((platform) => (
        <Chip key={platform} variant="flat" color="success" size={size}>
          {SUPPORTED_PLATFORM_MAP[platform]}
        </Chip>
      ))}
      {modelName && (
        <Chip variant="flat" color="danger" size={size}>
          {modelName}
        </Chip>
      )}
      {storage && (
        <Chip
          color="secondary"
          variant="flat"
          startContent={storageIcons[storage]}
        >
          {SUPPORTED_RESOURCE_LINK_MAP[storage as 's3' | 'user']}
        </Chip>
      )}
      {storageSize && (
        <Chip
          variant="flat"
          color="warning"
          startContent={<Database className="w-4 h-4" />}
        >
          {storageSize}
        </Chip>
      )}
      {!!downloadCount && (
        <Chip variant="flat" color="default" size={size}>
          {`${downloadCount} 人下载`}
        </Chip>
      )}
    </div>
  )
}
