// apps/next-web/components/kun/CardStats.tsx
import { Tooltip } from '@heroui/tooltip'
import { Download, Eye, Heart, MessageSquare, Puzzle } from 'lucide-react'
import { cn } from '~/utils/cn'
import { formatNumber } from '~/utils/formatNumber'

interface Props {
  patch: GalgameCard
  disableTooltip?: boolean
  isMobile?: boolean
}

export const KunCardStats = ({
  patch,
  disableTooltip = true,
  isMobile = true
}: Props) => {
  return (
    <div
      className={cn(
        'flex space-x-4 text-sm text-default-500',
        isMobile ? 'sm:justify-start' : ''
      )}
    >
      <Tooltip isDisabled={disableTooltip} content="浏览数" placement="bottom">
        <div className="flex items-center gap-1">
          <Eye className="size-4" />
          <span>{formatNumber(patch.view)}</span>
        </div>
      </Tooltip>

      <Tooltip isDisabled={disableTooltip} content="下载数" placement="bottom">
        <div className="flex items-center gap-1">
          <Download className="size-4" />
          <span>{formatNumber(patch.download)}</span>
        </div>
      </Tooltip>

      <Tooltip isDisabled={disableTooltip} content="收藏数" placement="bottom">
        <div
          className={cn(
            'items-center hidden gap-1',
            isMobile ? 'hidden sm:flex' : 'flex'
          )}
        >
          <Heart className="size-4" />
          <span>{formatNumber(patch._count.favorite_by || 0)}</span>
        </div>
      </Tooltip>

      <Tooltip
        isDisabled={disableTooltip}
        content="补丁资源数"
        placement="bottom"
      >
        <div className="flex items-center gap-1">
          <Puzzle className="size-4" />
          <span>{formatNumber(patch._count.resource || 0)}</span>
        </div>
      </Tooltip>

      <Tooltip isDisabled={disableTooltip} content="评论数" placement="bottom">
        <div
          className={cn(
            'items-center hidden gap-1',
            isMobile ? 'hidden sm:flex' : 'flex'
          )}
        >
          <MessageSquare className="size-4" />
          <span>{formatNumber(patch._count.comment || 0)}</span>
        </div>
      </Tooltip>
    </div>
  )
}

// apps/web/app/components/kun/CardStats.vue
<script setup lang="ts">
interface Props {
  patch: GalgameCard
  disableTooltip?: boolean
  isMobile?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  disableTooltip: true,
  isMobile: true
})
</script>

<template>
  <div
    :class="
      cn(
        'text-default-500 flex space-x-4 text-sm',
        props.isMobile ? 'sm:justify-start' : ''
      )
    "
  >
    <div class="flex items-center gap-1">
      <KunIcon name="lucide:eye" class="size-4" />
      <span>{{ formatNumber(props.patch.view) }}</span>
    </div>

    <div class="flex items-center gap-1">
      <KunIcon name="lucide:download" class="size-4" />
      <span>{{ formatNumber(props.patch.download) }}</span>
    </div>

    <div
      :class="
        cn(
          'hidden items-center gap-1',
          props.isMobile ? 'hidden sm:flex' : 'flex'
        )
      "
    >
      <KunIcon name="lucide:heart" class="size-4" />
      <span>{{ formatNumber(props.patch._count.favorite_by || 0) }}</span>
    </div>

    <div class="flex items-center gap-1">
      <KunIcon name="lucide:puzzle" class="size-4" />
      <span>{{ formatNumber(props.patch._count.resource || 0) }}</span>
    </div>

    <div
      :class="
        cn(
          'hidden items-center gap-1',
          props.isMobile ? 'hidden sm:flex' : 'flex'
        )
      "
    >
      <KunIcon name="lucide:message-square" class="size-4" />
      <span>{{ formatNumber(props.patch._count.comment || 0) }}</span>
    </div>
  </div>
</template>
