// components/kun/NavigationBreadcrumb.tsx
'use client'

import { useEffect } from 'react'
import {
  Button,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  DropdownTrigger
} from '@nextui-org/react'
import { BreadcrumbItem, Breadcrumbs } from '@nextui-org/breadcrumbs'
import { ChevronRight } from 'lucide-react'
import { useParams, usePathname } from 'next/navigation'
import { useBreadcrumbStore } from '~/store/breadcrumb'
import { createBreadcrumbItem } from '~/constants/routes/routes'
import { dynamicRoutes } from '~/constants/routes/constants'
import type { KunBreadcrumbItem } from '~/constants/routes/constants'

export const KunNavigationBreadcrumb = () => {
  const { items, setItems } = useBreadcrumbStore()
  const pathname = usePathname()
  const params = useParams()

  const handleRoutes = async () => {
    const newItem = createBreadcrumbItem(pathname, params)
    if (!newItem) {
      return
    }

    const mergedItems = [...items, newItem]
    const itemMap = new Map<string, KunBreadcrumbItem>()

    mergedItems.forEach((item) => {
      if (itemMap.has(item.key)) {
        const existingItem = itemMap.get(item.key)
        itemMap.delete(item.key)
        if (dynamicRoutes.includes(item.key)) {
          itemMap.set(item.key, item)
        } else {
          itemMap.set(item.key, existingItem!)
        }
      } else {
        itemMap.set(item.key, item)
      }
    })

    const dedupItems = Array.from(itemMap.values())
    setItems(dedupItems)
  }

  useEffect(() => {
    handleRoutes()
  }, [pathname])

  return (
    <div className="w-full my-4 bg-background/60 backdrop-blur-lg">
      <div className="px-6 mx-auto max-w-7xl">
        <Breadcrumbs
          underline="hover"
          separator={<ChevronRight className="size-4" />}
          itemClasses={{
            item: 'text-foreground/60 data-[current=true]:text-foreground'
          }}
          variant="light"
          radius="lg"
          renderEllipsis={({ items, ellipsisIcon, separator }) => (
            <div key="id" className="flex items-center">
              <Dropdown>
                <DropdownTrigger>
                  <Button
                    isIconOnly
                    className="size-6 min-w-6"
                    size="sm"
                    variant="flat"
                  >
                    {ellipsisIcon}
                  </Button>
                </DropdownTrigger>
                <DropdownMenu aria-label="Routes">
                  {items.map((item, index) => (
                    <DropdownItem
                      key={index}
                      textValue={index.toString()}
                      href={item.href}
                    >
                      <p className="break-all">{item.children}</p>
                    </DropdownItem>
                  ))}
                </DropdownMenu>
              </Dropdown>
              {separator}
            </div>
          )}
        >
          {items.map((item, index) => (
            <BreadcrumbItem
              key={item.key}
              isCurrent={index === items.length - 1}
              href={item.href}
            >
              {item.label}
            </BreadcrumbItem>
          ))}
        </Breadcrumbs>
      </div>
    </div>
  )
}

// apps/web/app/components/kun/NavigationBreadcrumb.vue
<script setup lang="ts">
import { createBreadcrumbItem } from '~/constants/routes/routes'
import { dynamicRoutes } from '~/constants/routes/constants'
import type { KunBreadcrumbItem } from '~/constants/routes/constants'

const route = useRoute()
const breadcrumbStore = useBreadcrumbStore()

const handleRoutes = () => {
  const newItem = createBreadcrumbItem(route.path, route.params)
  if (!newItem) return

  const merged = [...breadcrumbStore.items, newItem]
  const map = new Map<string, KunBreadcrumbItem>()

  for (const item of merged) {
    if (map.has(item.key)) {
      const existing = map.get(item.key)!
      map.delete(item.key)
      if (dynamicRoutes.some((r) => item.key.startsWith(`/${r}`))) {
        map.set(item.key, item)
      } else {
        map.set(item.key, existing)
      }
    } else {
      map.set(item.key, item)
    }
  }

  breadcrumbStore.setItems(Array.from(map.values()))
}

watch(() => route.path, handleRoutes, { immediate: true })
</script>

<template>
  <div class="z-10 my-4 w-full">
    <div class="mx-auto max-w-7xl px-3">
      <ol class="flex flex-wrap items-center gap-1 text-sm">
        <template
          v-for="(item, index) in breadcrumbStore.items"
          :key="item.key"
        >
          <li class="flex items-center">
            <NuxtLink
              :to="item.href"
              :class="
                cn(
                  'hover:bg-default-100 rounded px-2 py-1 break-all hover:underline',
                  index === breadcrumbStore.items.length - 1
                    ? 'text-foreground font-medium'
                    : 'text-foreground/60'
                )
              "
            >
              {{ item.label }}
            </NuxtLink>
          </li>
          <li
            v-if="index < breadcrumbStore.items.length - 1"
            class="text-foreground/40"
          >
            <KunIcon name="lucide:chevron-right" class="size-4" />
          </li>
        </template>
      </ol>
    </div>
  </div>
</template>
