// apps/web/components/home/PatchCard.tsx
import Link from 'next/link'
import { Card, CardBody } from '@heroui/card'
import { Image } from '@heroui/image'
import { KunCardStats } from '~/components/kun/CardStats'
import { getPreferredLanguageText } from '~/utils/getPreferredLanguageText'

interface Props {
  patch: GalgameCard
}

export const PatchCard = ({ patch }: Props) => {
  const galgameName = getPreferredLanguageText(patch.name)

  return (
    <Card
      isPressable
      as={Link}
      href={`/patch/${patch.id}/introduction`}
      className="w-full"
    >
      <CardBody className="p-4">
        <div className="flex flex-col gap-4 sm:flex-row">
          <div className="relative w-full sm:w-40">
            <Image
              removeWrapper
              src={patch.banner.replace(/\.avif$/, '-mini.avif')}
              alt={galgameName}
              className="object-cover rounded-lg size-full"
              radius="lg"
            />
          </div>
          <div className="flex-1 space-y-3">
            <h2 className="text-lg font-semibold transition-colors line-clamp-2 hover:text-primary-500">
              {galgameName}
            </h2>

            <KunCardStats patch={patch} />
          </div>
        </div>
      </CardBody>
    </Card>
  )
}

// apps/web/app/components/home/PatchCard.vue
<script setup lang="ts">
interface Props {
  patch: GalgameCard
}

const props = defineProps<Props>()

const galgameName = computed(() => getPreferredLanguageText(props.patch.name))

const bannerSrc = computed(() =>
  props.patch.banner.replace(/\.avif$/, '-mini.avif')
)
</script>

<template>
  <KunCard
    is-pressable
    :href="`/patch/${props.patch.id}/introduction`"
    class-name="w-full"
  >
    <div class="flex flex-col gap-4 p-4 sm:flex-row">
      <div class="relative w-full sm:w-40">
        <KunImage
          :src="bannerSrc"
          :alt="galgameName"
          class-name="size-full rounded-lg object-cover"
        />
      </div>
      <div class="flex-1 space-y-3">
        <h2
          class="hover:text-primary-500 text-lg font-semibold transition-colors line-clamp-2"
        >
          {{ galgameName }}
        </h2>

        <KunCardStats :patch="props.patch" />
      </div>
    </div>
  </KunCard>
</template>
