// components/kun/ad/AIEroBanner.tsx
import { Image } from '@heroui/image'
import { kunMoyuMoe } from '~/config/moyu-moe'
import { cn } from '~/utils/cn'
import type { KunGalgamePayload } from '~/app/api/utils/jwt'

interface Props {
  payload: KunGalgamePayload | null
  className?: string
}

export const AIEroBanner = ({ payload, className = '' }: Props) => {
  return (
    <>
      {(!payload || payload.role < 2) && (
        <div className={cn('shadow-xl rounded-2xl', className)}>
          <a
            target="_blank"
            className="h-full w-full"
            href={kunMoyuMoe.ad[0].url}
            rel="noreferrer"
          >
            <Image
              className="pointer-events-none select-none"
              src="/a/moyumoe1.avif"
              alt=""
            />
          </a>
        </div>
      )}
    </>
  )
}

// apps/web/app/components/kun/ad/AIEroBanner.vue
<script setup lang="ts">
import { kunMoyuMoe } from '~/config/moyu-moe'

interface Props {
  className?: string
}
const props = withDefaults(defineProps<Props>(), { className: '' })

const userStore = useUserStore()
</script>

<template>
  <div
    v-if="!userStore.isAdFree"
    :class="cn('overflow-hidden rounded-2xl shadow-xl', props.className)"
  >
    <a
      :href="kunMoyuMoe.ad[0]?.url"
      target="_blank"
      rel="noopener noreferrer"
      class="block h-full w-full"
    >
      <KunImage
        src="/a/moyumoe1.avif"
        alt=""
        provider="none"
        aspect-ratio="1920 / 300"
        class-name="w-full"
        image-class-name="pointer-events-none select-none"
      />
    </a>
  </div>
</template>
