// components/about/BlogHeader.tsx
import { Alert } from "@heroui/alert"
import { Card, CardBody, CardHeader } from "@heroui/card"
import { Image } from "@heroui/image"
import { CalendarDays } from 'lucide-react'
import { formatDate } from '~/utils/time'
import { KunAvatar } from '~/components/kun/floating-card/KunAvatar'
import type { KunFrontmatter } from '~/lib/mdx/types'

interface BlogHeaderProps {
  frontmatter: KunFrontmatter
}

export const BlogHeader = ({ frontmatter }: BlogHeaderProps) => {
  return (
    <Card className="w-full space-y-4 overflow-visible bg-transparent border-none shadow-none">
      <CardHeader className="flex flex-col items-start p-0">
        <div className="relative w-full overflow-hidden rounded-xl">
          <Image
            isZoomed
            alt={frontmatter.title}
            className="object-cover"
            src={frontmatter.banner}
            width="100%"
            height="100%"
          />
        </div>
      </CardHeader>

      <CardBody className="p-0 overflow-visible">
        <div className="flex flex-col space-y-4">
          <h1 className="text-2xl font-bold tracking-tight sm:text-4xl">
            {frontmatter.title}
          </h1>

          <div className="flex items-center gap-3">
            <KunAvatar
              uid={frontmatter.authorUid}
              avatarProps={{
                isBordered: true,
                radius: 'full',
                size: 'md',
                name: frontmatter.authorName,
                src: frontmatter.authorAvatar,
                className: 'shrink-0'
              }}
            />
            <div className="flex flex-col gap-1">
              <h2 className="font-semibold leading-none text-small">
                {frontmatter.authorName}
              </h2>
              <div className="flex items-center gap-2">
                <CalendarDays className="w-4 h-4 text-default-400" />
                <p className="text-small text-default-400">
                  {formatDate(frontmatter.date, {
                    isPrecise: true,
                    isShowYear: true
                  })}
                </p>
              </div>
            </div>
          </div>

          <Alert
            hideIcon
            description={frontmatter.description}
            color="primary"
          />
        </div>
      </CardBody>
    </Card>
  )
}

// apps/web/app/components/about/BlogHeader.vue
<script setup lang="ts">
interface Props {
  frontmatter: KunPostFrontmatter
}

const props = defineProps<Props>()
</script>

<template>
  <header class="w-full space-y-4">
    <div
      v-if="props.frontmatter.banner"
      class="relative w-full overflow-hidden rounded-xl"
    >
      <KunImage
        :src="props.frontmatter.banner"
        :alt="props.frontmatter.title"
        provider="none"
        loading="eager"
        fetchpriority="high"
        aspect-ratio="16 / 9"
        class-name="w-full"
      />
    </div>

    <h1 class="mt-8 text-2xl font-bold tracking-tight sm:text-4xl">
      {{ props.frontmatter.title }}
    </h1>

    <div class="flex items-center gap-3">
      <KunImage
        v-if="props.frontmatter.author_avatar"
        :src="props.frontmatter.author_avatar"
        :alt="props.frontmatter.author_name"
        :skeleton="false"
        class-name="border-default-200 size-10 shrink-0 rounded-full border-2"
      />
      <div class="flex flex-col gap-1">
        <h2 class="text-sm leading-none font-semibold">
          {{ props.frontmatter.author_name }}
        </h2>
        <div class="text-default-400 flex items-center gap-2 text-sm">
          <KunIcon name="lucide:calendar-days" class="size-4" />
          <p>
            {{
              props.frontmatter.date
                ? formatDate(props.frontmatter.date, {
                    isPrecise: true,
                    isShowYear: true
                  })
                : ''
            }}
          </p>
        </div>
      </div>
    </div>

    <KunInfo
      v-if="props.frontmatter.description"
      color="primary"
      variant="flat"
      :description="props.frontmatter.description"
    />
  </header>
</template>
