// apps/web/app/pages/login.vue
<script setup lang="ts">
import { kunMoyuMoe } from '~/config/moyu-moe'

useKunSeoMeta({
  title: '登录',
  description: '登录到 鲲 Galgame 补丁'
})
</script>

<template>
  <div class="mx-auto flex items-center justify-center">
    <KunCard class-name="w-full max-w-md" :bordered="false">
      <template #header>
        <div class="flex flex-col items-center space-y-6 pt-8">
          <div
            class="text-default-500 text-medium flex cursor-default items-center space-x-2 font-medium"
          >
            <KunImage
              src="/favicon.webp"
              :alt="kunMoyuMoe.titleShort"
              :width="36"
              :height="36"
              class-name="rounded-2xl"
            />
            <span>{{ kunMoyuMoe.titleShort }}</span>
          </div>

          <h1 class="text-3xl font-bold">登录</h1>
        </div>
      </template>

      <div class="flex justify-center px-8 py-6">
        <LoginForm />
      </div>
    </KunCard>
  </div>
</template>

// app/login/page.tsx
import { LoginForm } from '~/components/login/Login'
import { kunMetadata } from './metadata'
import { Card, CardBody, CardHeader } from '@heroui/card'
import Image from 'next/image'
import { kunMoyuMoe } from '~/config/moyu-moe'
import type { Metadata } from 'next'

export const metadata: Metadata = kunMetadata

export default function Kun() {
  return (
    <div className="flex items-center justify-center mx-auto">
      <Card className="w-full max-w-md">
        <CardHeader className="flex flex-col items-center pt-8 space-y-6">
          <div className="flex items-center space-x-2 font-medium cursor-default text-medium text-default-500">
            <Image
              src="/favicon.webp"
              priority={true}
              alt={kunMoyuMoe.titleShort}
              width={36}
              height={36}
              className="rounded-2xl"
            />
            <span>{kunMoyuMoe.titleShort}</span>
          </div>

          <h1 className="text-3xl font-bold">登录</h1>
        </CardHeader>
        <CardBody className="flex justify-center px-8 py-6">
          <LoginForm />
        </CardBody>
      </Card>
    </div>
  )
}
