// components/patch/resource/Resource.tsx
'use client'

import { useState, useEffect } from 'react'
import { Chip } from '@nextui-org/chip'
import { Button } from '@nextui-org/button'
import { Card, CardBody } from '@nextui-org/card'
import { Snippet } from '@nextui-org/snippet'
import { User } from '@nextui-org/user'
import { Link } from '@nextui-org/link'
import { Heart, MoreHorizontal, Plus, Download } from 'lucide-react'
import { api } from '~/lib/trpc-client'
import { PublishResource } from './PublishResource'
import type { PatchResource } from '~/types/api/patch'

export const Resources = ({ id }: { id: number }) => {
  const [resources, setResources] = useState<PatchResource[]>([])
  const [showCreate, setShowCreate] = useState(false)
  const [showLinks, setShowLinks] = useState<Record<number, boolean>>({})

  const fetchResources = async () => {
    const res = await api.patch.getPatchResource.query({
      patchId: Number(id)
    })
    setResources(res)
  }

  useEffect(() => {
    fetchResources()
  }, [id])

  const toggleLinks = (resourceId: number) => {
    setShowLinks((prev) => ({
      ...prev,
      [resourceId]: !prev[resourceId]
    }))
  }

  return (
    <div className="space-y-4">
      <div className="flex justify-end">
        <Button
          color="primary"
          variant="flat"
          startContent={<Plus className="w-4 h-4" />}
          onPress={() => setShowCreate(!showCreate)}
        >
          添加资源
        </Button>
      </div>

      {showCreate && (
        <PublishResource
          patchId={id}
          onSuccess={() => {
            setShowCreate(false)
            fetchResources()
          }}
        />
      )}

      {resources.map((resource) => (
        <Card key={resource.id}>
          <CardBody className="space-y-2">
            <div className="flex items-start justify-between">
              <div className="space-y-2">
                <div className="flex flex-wrap gap-2">
                  {resource.type.map((type) => (
                    <Chip key={type} variant="flat">
                      {type}
                    </Chip>
                  ))}
                  {resource.language.map((lang) => (
                    <Chip key={lang} variant="bordered">
                      {lang}
                    </Chip>
                  ))}
                  {<Chip variant="flat">{resource.size}</Chip>}
                </div>

                <div className="flex flex-wrap gap-2">
                  <Snippet
                    tooltipProps={{
                      content: '点击复制提取码'
                    }}
                    size="sm"
                    symbol="提取码"
                    color="primary"
                  >
                    {resource.code}
                  </Snippet>

                  <Snippet
                    tooltipProps={{
                      content: '点击复制解压码'
                    }}
                    size="sm"
                    symbol="解压码"
                    color="primary"
                  >
                    {resource.password}
                  </Snippet>
                </div>

                {resource.note && <p className="mt-2">{resource.note}</p>}
              </div>

              <Button variant="light" isIconOnly className="text-default-400">
                <MoreHorizontal className="w-4 h-4" />
              </Button>
            </div>

            <div className="flex justify-between">
              <User
                name={resource.user.name}
                description={`已发布补丁 ${resource.user.patchCount} 个`}
                avatarProps={{
                  showFallback: true,
                  src: resource.user.avatar,
                  name: resource.user.name.charAt(0).toUpperCase()
                }}
              />

              <div className="flex gap-2">
                <Button variant="bordered" isIconOnly>
                  <Heart className="w-4 h-4" />
                </Button>
                <Button
                  variant="bordered"
                  isIconOnly
                  onPress={() => toggleLinks(resource.id)}
                >
                  <Download className="w-4 h-4" />
                </Button>
              </div>
            </div>

            {showLinks[resource.id] && (
              <div className="flex flex-wrap gap-2 mt-4">
                {resource.link.map((link, index) => (
                  <Button
                    key={index}
                    as={Link}
                    href={link}
                    showAnchorIcon
                    color="primary"
                    variant="solid"
                  >
                    下载链接 {index + 1}
                  </Button>
                ))}
              </div>
            )}
          </CardBody>
        </Card>
      ))}
    </div>
  )
}

// apps/web/app/pages/patch/[id]/resource.vue
<script setup lang="ts">
const route = useRoute()
const api = useApi()

const patchId = computed(() => Number(route.params.id))

const { data: resources, pending } = await useAsyncData<PatchResource[]>(
  () => `patch-resource-${patchId.value}`,
  async () => {
    const res = await api.get<PatchResource[]>(
      `/patch/${patchId.value}/resource`
    )
    return res.code === 0 ? res.data : []
  },
  { default: () => [] }
)
</script>

<template>
  <div class="space-y-4">
    <KunLoading v-if="pending" description="正在获取补丁资源..." />
    <div v-else-if="resources && resources.length" class="space-y-3">
      <div
        v-for="r in resources"
        :key="r.id"
        class="border-default/20 space-y-3 rounded-lg border p-4"
      >
        <div class="flex flex-wrap items-start justify-between gap-2">
          <div>
            <h3 class="text-lg font-semibold line-clamp-2">
              {{ r.name || '补丁资源' }}
            </h3>
            <div class="text-default-500 text-xs">
              由 {{ r.user.name }} 发布于
              {{ formatDate(r.created, { isShowYear: true, isPrecise: true }) }}
            </div>
          </div>
          <KunBadge size="sm" variant="flat">{{ r.size }}</KunBadge>
        </div>

        <KunPatchAttribute
          :types="r.type"
          :languages="r.language"
          :platforms="r.platform"
          :model-name="r.modelName"
          :storage="r.storage"
          size="sm"
        />

        <p v-if="r.note" class="text-default-500 text-sm whitespace-pre-wrap">
          {{ r.note }}
        </p>

        <div
          v-if="r.code || r.password"
          class="text-default-500 flex flex-wrap gap-4 text-sm"
        >
          <span v-if="r.code">提取码: {{ r.code }}</span>
          <span v-if="r.password">解压密码: {{ r.password }}</span>
        </div>

        <div v-if="r.hash" class="text-default-400 break-all text-xs">
          Hash: {{ r.hash }}
          <NuxtLink
            :to="`/check-hash?hash=${r.hash}&content=${encodeURIComponent(r.content || '')}`"
            class="text-primary ml-2 hover:underline"
          >
            校验文件
          </NuxtLink>
        </div>

        <div
          class="text-default-500 flex flex-wrap items-center justify-between gap-2 pt-2 text-sm"
        >
          <div class="flex items-center gap-4">
            <div class="flex items-center gap-1">
              <KunIcon name="lucide:heart" class="size-4" />
              {{ r.likeCount }}
            </div>
            <div class="flex items-center gap-1">
              <KunIcon name="lucide:download" class="size-4" />
              {{ r.download }}
            </div>
          </div>
          <NuxtLink :to="`/resource/${r.id}`">
            <KunButton color="primary" size="sm">
              <KunIcon name="lucide:download" class="size-4" />
              下载
            </KunButton>
          </NuxtLink>
        </div>
      </div>
    </div>
    <KunNull v-else description="该 Galgame 暂无补丁资源" />
  </div>
</template>
