// components/user/contribute/Card.tsx
import { Card, CardBody } from "@heroui/card"
import { formatDate } from '~/utils/time'
import Link from 'next/link'
import type { UserContribute } from '~/types/api/user'

interface Props {
  contribute: UserContribute
}

export const UserContributeCard = ({ contribute }: Props) => {
  return (
    <Card
      isPressable
      as={Link}
      href={`/patch/${contribute.patchId}/history`}
      target="_blank"
      className="w-full"
    >
      <CardBody className="p-4 space-y-3">
        <h2 className="text-lg font-semibold transition-colors line-clamp-2 hover:text-primary-500">
          {contribute.patchName}
        </h2>
        <p className="text-sm text-default-500">
          贡献于{' '}
          {formatDate(contribute.created, {
            isPrecise: true,
            isShowYear: true
          })}
        </p>
      </CardBody>
    </Card>
  )
}

// apps/web/app/components/comment/Card.vue
<script setup lang="ts">
interface Props {
  comment: PatchComment
}

const props = defineProps<Props>()

const patchName = computed(() =>
  getPreferredLanguageText(props.comment.patchName)
)
</script>

<template>
  <KunCard
    is-pressable
    :href="`/patch/${props.comment.patchId}/comment`"
    class-name="w-full"
  >
    <div class="flex gap-4">
      <KunAvatar :user="props.comment.user" />
      <div class="space-y-2">
        <div class="flex flex-wrap items-center gap-2">
          <h2 class="font-semibold">{{ props.comment.user.name }}</h2>
          <span class="text-small text-default-500">
            评论在
            <span class="text-primary-500">{{ patchName }}</span>
          </span>
        </div>
        <p class="mt-1">{{ props.comment.content }}</p>
        <div class="mt-2 flex items-center gap-4">
          <div class="text-small text-default-500 flex items-center gap-1">
            <KunIcon name="lucide:thumbs-up" class="size-3.5" />
            {{ props.comment.like }}
          </div>
          <span class="text-small text-default-500">
            {{
              formatDate(props.comment.created, {
                isPrecise: true,
                isShowYear: true
              })
            }}
          </span>
        </div>
      </div>
    </div>
  </KunCard>
</template>
