// apps/web/app/components/about/SideTreeItem.vue
<script setup lang="ts">
interface Props {
  node: KunTreeNode
  level?: number
  activeSlug?: string
}

const props = withDefaults(defineProps<Props>(), { level: 0, activeSlug: '' })

const isOpen = ref(
  props.node.type === 'directory' &&
    (props.level === 0 ||
      (!!props.activeSlug && props.activeSlug.startsWith(props.node.path + '/')))
)

const toggle = () => {
  if (props.node.type === 'directory') isOpen.value = !isOpen.value
}

const isActive = computed(
  () => props.node.type === 'file' && props.node.path === props.activeSlug
)

const indentPx = computed(() => `${props.level * 12 + 12}px`)

const rowClass = computed(() => [
  'hover:bg-default-100 mt-1 flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left transition-colors',
  isActive.value ? 'bg-primary/10 text-primary font-medium' : 'text-foreground'
])
</script>

<template>
  <div class="select-none">
    <NuxtLink
      v-if="props.node.type === 'file'"
      :to="`/doc/${props.node.path}`"
      :class="rowClass"
      :style="{ paddingLeft: indentPx }"
    >
      <KunIcon
        name="lucide:file-text"
        class="text-primary ml-5 size-4 shrink-0"
      />
      <span class="text-sm leading-tight break-words">
        {{ props.node.label || props.node.name }}
      </span>
    </NuxtLink>

    <KunButton
      v-else
      variant="light"
      color="default"
      size="sm"
      full-width
      rounded="md"
      :class-name="cn('justify-start', rowClass)"
      :style="{ paddingLeft: indentPx }"
      @click="toggle"
    >
      <KunIcon
        name="lucide:chevron-right"
        :class="cn('size-4 transition-transform duration-200', isOpen && 'rotate-90')"
      />
      <KunIcon name="lucide:folder-open" class="text-warning size-4" />
      <span class="text-sm leading-tight break-words">
        {{ props.node.label || props.node.name }}
      </span>
    </KunButton>

    <div
      v-if="props.node.type === 'directory' && isOpen && props.node.children?.length"
    >
      <AboutSideTreeItem
        v-for="(child, i) in props.node.children"
        :key="i"
        :node="child"
        :level="props.level + 1"
        :active-slug="props.activeSlug"
      />
    </div>
  </div>
</template>

// components/about/SideTreeItem.tsx
'use client'

import { useState } from 'react'
import { Link } from '@heroui/link'
import { KunTreeNode } from '~/lib/mdx/types'
import { ChevronRight, FileText, FolderOpen } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { cn } from '~/utils/cn'

interface TreeItemProps {
  node: KunTreeNode
  level: number
}

export const TreeItem = ({ node, level }: TreeItemProps) => {
  const router = useRouter()
  const [isOpen, setIsOpen] = useState(true)

  const handleClick = () => {
    if (node.type === 'directory') {
      setIsOpen(!isOpen)
    } else {
      router.push(`/about/${node.path}`)
    }
  }

  return (
    <nav className="select-none">
      <Link
        className={cn(
          'w-full justify-start gap-2 px-3 py-2 cursor-pointer rounded-xl',
          level === 0 ? 'mt-0' : 'mt-1',
          'hover:bg-default/40'
        )}
        style={{ paddingLeft: `${level * 12 + 12}px` }}
        onPress={handleClick}
        color="foreground"
      >
        <div className="flex items-center gap-2">
          {node.type === 'directory' ? (
            <>
              <ChevronRight
                size={16}
                className={`transition-transform duration-200 ${
                  isOpen ? 'rotate-90' : ''
                }`}
              />
              <FolderOpen size={16} className="text-warning" />
            </>
          ) : (
            <FileText size={16} className="ml-5 text-primary shrink-0" />
          )}
          <span className="text-sm text-left text-wrap">{node.label}</span>
        </div>
      </Link>

      {node.type === 'directory' && isOpen && (
        <div className="overflow-hidden">
          {node.children?.map((child, index) => (
            <TreeItem key={index} node={child} level={level + 1} />
          ))}
        </div>
      )}
    </nav>
  )
}
