// apps/web/components/kun/top-bar/Brand.tsx
import { NavbarBrand } from '@heroui/navbar'
import { Tooltip } from '@heroui/tooltip'
import { Chip } from '@heroui/chip'
import { kunMoyuMoe } from '~/config/moyu-moe'
import Image from 'next/image'
import Link from 'next/link'

export const KunTopBarBrand = () => {
  return (
    <Tooltip
      disableAnimation
      showArrow
      closeDelay={0}
      placement="bottom-start"
      content={
        <div className="px-1 py-2 space-y-1">
          <div className="font-bold text-small">如何记住本站的域名?</div>
          <div className="text-tiny">{`鲲喜欢摸鱼 -> 摸鱼(moyu) . 萌(moe)`}</div>
          <div className="text-tiny">当然您也可以 Ctrl + D 收藏本站网址</div>
        </div>
      }
    >
      <NavbarBrand className="hidden grow-0 md:flex">
        <Link className="flex items-center" href="/">
          <Image
            src="/favicon.webp"
            alt={kunMoyuMoe.titleShort}
            width={50}
            height={50}
            priority
            className="rounded-2xl shrink-0"
          />
          <p className="ml-4 hidden lg:block mr-2 font-bold text-inherit">
            {kunMoyuMoe.creator.name}
          </p>
          <Chip
            className="hidden lg:flex"
            size="sm"
            variant="flat"
            color="primary"
          >
            补丁
          </Chip>
        </Link>
      </NavbarBrand>
    </Tooltip>
  )
}

// apps/web/app/components/kun/top-bar/Brand.vue
<script setup lang="ts">
import { kunMoyuMoe } from '~/config/moyu-moe'
</script>

<template>
  <KunTooltip position="bottom">
    <template #content>
      <div class="space-y-1 px-1 py-2">
        <div class="text-small font-bold">如何记住本站的域名?</div>
        <div class="text-tiny text-foreground/80">
          鲲喜欢摸鱼 -&gt; 摸鱼(moyu) . 萌(moe)
        </div>
        <div class="text-tiny text-foreground/60">
          当然您也可以 Ctrl + D 收藏本站网址
        </div>
      </div>
    </template>

    <NuxtLink class="hidden items-center md:flex" to="/">
      <KunImage
        src="/favicon.webp"
        :alt="kunMoyuMoe.titleShort"
        :width="50"
        :height="50"
        class-name="shrink-0 rounded-2xl"
      />
      <p class="mr-2 ml-4 hidden font-bold lg:block">
        {{ kunMoyuMoe.creator.name }}
      </p>
      <KunBadge
        class="hidden lg:flex"
        size="sm"
        variant="flat"
        color="primary"
      >
        补丁
      </KunBadge>
    </NuxtLink>
  </KunTooltip>
</template>
