// components/edit/create/ContentLimit.tsx
'use client'

import { Switch, Alert, Image, CardBody, Card } from '@heroui/react'
import { useCreatePatchStore } from '~/store/editStore'
import { GALGAME_AGE_LIMIT_MAP } from '~/constants/galgame'

interface Props {
  errors: string | undefined
}

export const ContentLimit = ({ errors }: Props) => {
  const { data, setData } = useCreatePatchStore()

  return (
    <div className="space-y-2">
      <h2 className="text-xl">页面内容分级</h2>
      <Alert
        color="danger"
        title="再次请大家注意 NSFW 问题"
        description="网站目前的 NSFW 认定标准可能比较苛刻, 看起来不能在公司报告大会上放在 PPT 里展示的游戏都是 NSFW ,封面需要打码才能放上去的一律算 NSFW, 总之就是越严越好，可以错杀不可以放过，因为会导致网站违反 Google 或 Bing 的条款"
      />

      <Card>
        <CardBody>
          {errors && <p className="text-xs text-danger-500">{errors}</p>}
          <p className="text-sm text-default-500">
            默认游戏页面是 SFW (内容安全, 可以在公告场合打开),
            如果您觉得游戏名、预览图、介绍等过于虎狼 (例如:
            用淫乱喷雾强制贞淑人妻们发情), 页面完全没有办法在公共场合展示,
            请将内容分级为 NSFW (内容可能有 R18, 会导致社死)
          </p>
          <p className="text-sm text-default-500">
            NSFW 指的是游戏页面含有不适合在公共场合展示的内容,
            而不是指的游戏本身含有 R18 内容
          </p>
          <p className="text-sm text-default-500">
            SFW 的浏览量会高两到三倍,
            因此请您尽量保证游戏封面、游戏名、游戏介绍等可以在公共场合展示
          </p>
          <p className="text-sm text-default-500 font-bold">
            例如下面两张图就算作 NSFW 的游戏, 有 NSFW 的游戏名或介绍等等也算作
            NSFW
          </p>
          <div className="flex gap-2">
            <Image alt="nsfw-image2" src="/edit/1.avif" width={200} />
            <Image alt="nsfw-image2" src="/edit/2.avif" width={200} />
          </div>
        </CardBody>
      </Card>

      <p>注意这个 NSFW 开关, 越严越好, 只要有一点不对立即设置为 NSFW</p>
      <Switch
        defaultSelected
        color="danger"
        size="lg"
        isSelected={data.contentLimit === 'nsfw'}
        onValueChange={(value) => {
          if (value) {
            setData({ ...data, contentLimit: 'nsfw' })
          } else {
            setData({ ...data, contentLimit: 'sfw' })
          }
        }}
      >
        {GALGAME_AGE_LIMIT_MAP[data.contentLimit]}
      </Switch>
    </div>
  )
}

// apps/web/app/components/edit/create/ContentLimit.vue
<script setup lang="ts">
import { GALGAME_AGE_LIMIT_MAP } from '~/constants/galgame'

interface Props {
  errors?: string
}

defineProps<Props>()

const store = useCreatePatchStore()

const isNsfw = computed({
  get: () => store.data.contentLimit === 'nsfw',
  set: (v: boolean) => store.setData({ contentLimit: v ? 'nsfw' : 'sfw' })
})
</script>

<template>
  <div class="space-y-2">
    <h2 class="text-xl">页面内容分级</h2>
    <div
      class="border-danger/30 bg-danger/5 rounded-lg border p-3 text-sm"
    >
      <p class="text-danger font-bold">再次请大家注意 NSFW 问题</p>
      <p class="text-default-600 mt-1">
        封面需要打码才能放上去的一律算 NSFW, 看起来不能在公司报告大会上放在 PPT 里展示的游戏都是 NSFW, 可以错杀不可以放过
      </p>
    </div>

    <KunCard :bordered="true">
      <p v-if="errors" class="text-danger-500 text-xs">{{ errors }}</p>
      <p class="text-default-500 text-sm">
        默认页面是 SFW (内容安全), 如果觉得游戏名/预览图/介绍过于虎狼, 完全无法在公共场合展示, 请设置为 NSFW
      </p>
      <p class="text-default-500 text-sm">
        SFW 的浏览量会高两到三倍, 请尽量保证游戏封面、游戏名、游戏介绍等可以在公共场合展示
      </p>
    </KunCard>

    <p>注意这个 NSFW 开关, 越严越好, 只要有一点不对立即设置为 NSFW</p>
    <KunSwitch v-model="isNsfw" :label="GALGAME_AGE_LIMIT_MAP[store.data.contentLimit]" />
  </div>
</template>
