// components/galgame/Card.tsx
'use client'

import { useState } from 'react'
import { Card, CardBody, CardFooter, CardHeader } from '@heroui/card'
import { Chip } from '@heroui/chip'
import { Image } from '@heroui/image'
import { KunCardStats } from '~/components/kun/CardStats'
import Link from 'next/link'
import { KunPatchAttribute } from '~/components/kun/PatchAttribute'
import { cn } from '~/utils/cn'
import { GALGAME_AGE_LIMIT_MAP } from '~/constants/galgame'
import { formatDistanceToNow } from '~/utils/formatDistanceToNow'

interface Props {
  patch: GalgameCard
}

export const GalgameCard = ({ patch }: Props) => {
  const [imageLoaded, setImageLoaded] = useState(false)

  return (
    <Card
      isPressable
      as={Link}
      href={`/patch/${patch.id}/introduction`}
      className="w-full border border-default-100 dark:border-default-200"
    >
      <CardHeader className="p-0">
        <div className="relative w-full mx-auto overflow-hidden text-center rounded-t-lg opacity-90">
          <div
            className={cn(
              'absolute inset-0 animate-pulse bg-default-100',
              imageLoaded ? 'opacity-0' : 'opacity-90',
              'transition-opacity duration-300'
            )}
            style={{ aspectRatio: '16/9' }}
          />
          <Image
            radius="none"
            alt={patch.name}
            className={cn(
              'size-full object-cover transition-all duration-300',
              imageLoaded ? 'scale-100 opacity-90' : 'scale-105 opacity-0'
            )}
            removeWrapper={true}
            src={
              patch.banner
                ? patch.banner.replace(/\.avif$/, '-mini.avif')
                : '/kungalgame.avif'
            }
            style={{ aspectRatio: '16/9' }}
            onLoad={() => setImageLoaded(true)}
          />

          <div className="absolute z-10 rounded-full bg-background left-2 top-2">
            <Chip
              color={patch.content_limit === 'sfw' ? 'success' : 'danger'}
              variant="flat"
            >
              {GALGAME_AGE_LIMIT_MAP[patch.content_limit]}
            </Chip>
          </div>

          <div className="absolute z-10 rounded-full bg-background right-2 bottom-2">
            <Chip size="sm" variant="flat">
              {formatDistanceToNow(patch.created)}
            </Chip>
          </div>
        </div>
      </CardHeader>
      <CardBody className="justify-between space-y-2">
        <h2 className="font-semibold transition-colors text-medium sm:text-lg line-clamp-2 hover:text-primary-500">
          {patch.name}
        </h2>
        <KunCardStats patch={patch} />
      </CardBody>
      <CardFooter className="pt-0">
        <KunPatchAttribute
          types={patch.type}
          languages={patch.language}
          platforms={patch.platform}
          size="sm"
        />
      </CardFooter>
    </Card>
  )
}

// apps/web/app/components/galgame/Card.vue
<script setup lang="ts">
import { GALGAME_AGE_LIMIT_MAP } from '~/constants/galgame'

interface Props {
  patch: GalgameCard
}

const props = defineProps<Props>()

const galgameName = computed(() => getPreferredLanguageText(props.patch.name))

const imageLoaded = ref(false)

const bannerSrc = computed(() =>
  props.patch.banner
    ? props.patch.banner.replace(/\.avif$/, '-mini.avif')
    : '/kungalgame-trans.webp'
)
</script>

<template>
  <KunCard
    is-pressable
    :href="`/patch/${props.patch.id}/introduction`"
    class-name="w-full border-default-100 dark:border-default-200 border"
    content-class="gap-0 p-0"
  >
    <div
      class="relative mx-auto w-full overflow-hidden rounded-t-lg text-center opacity-90"
    >
      <div
        :class="
          cn(
            'bg-default-100 absolute inset-0 animate-pulse',
            imageLoaded ? 'opacity-0' : 'opacity-90',
            'transition-opacity duration-300'
          )
        "
        style="aspect-ratio: 16 / 9"
      />
      <KunImage
        :alt="galgameName"
        :src="bannerSrc"
        :class="
          cn(
            'size-full object-cover transition-all duration-300',
            imageLoaded ? 'scale-100 opacity-90' : 'scale-105 opacity-0'
          )
        "
        style="aspect-ratio: 16 / 9"
        @load="imageLoaded = true"
      />

      <div class="bg-background absolute top-2 left-2 z-10 rounded-full">
        <KunBadge
          :color="props.patch.content_limit === 'sfw' ? 'success' : 'danger'"
          variant="flat"
        >
          {{ GALGAME_AGE_LIMIT_MAP[props.patch.content_limit] }}
        </KunBadge>
      </div>
    </div>

    <div class="flex flex-col justify-between space-y-2 p-3">
      <h2
        class="text-medium hover:text-primary-500 space-x-2 font-semibold transition-colors line-clamp-2 sm:text-lg"
      >
        <span>{{ galgameName }}</span>
        <span class="text-default-500 text-xs font-normal">
          {{ formatDistanceToNow(props.patch.created) }}
        </span>
      </h2>
      <KunCardStats :patch="props.patch" />
    </div>

    <div class="px-3 pt-0 pb-3">
      <KunPatchAttribute
        :types="props.patch.type"
        :languages="props.patch.language"
        :platforms="props.patch.platform"
        size="sm"
      />
    </div>
  </KunCard>
</template>
