// components/user/galgame/Card.tsx
import { Chip } from '@heroui/chip'
import { Card, CardBody } from '@heroui/card'
import { Image } from '@heroui/image'
import Link from 'next/link'
import { formatDistanceToNow } from '~/utils/formatDistanceToNow'
import { KunCardStats } from '~/components/kun/CardStats'
import { SUPPORTED_TYPE_MAP } from '~/constants/resource'

interface Props {
  galgame: GalgameCard
}

export const UserGalgameCard = ({ galgame }: Props) => {
  return (
    <Card
      isPressable
      as={Link}
      href={`/patch/${galgame.id}/introduction`}
      target="_blank"
      className="w-full"
    >
      <CardBody className="p-4">
        <div className="flex flex-col gap-4 sm:flex-row">
          <div className="relative w-full sm:h-auto sm:w-40">
            <Image
              src={
                galgame.banner
                  ? galgame.banner.replace(/\.avif$/, '-mini.avif')
                  : '/kungalgame.avif'
              }
              alt={galgame.name}
              className="object-cover rounded-lg size-full max-h-52"
              radius="lg"
            />
          </div>
          <div className="flex-1 space-y-3">
            <div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-center">
              <h2 className="text-lg font-semibold transition-colors line-clamp-2 hover:text-primary-500">
                {galgame.name}
              </h2>
              <Chip variant="flat">{formatDistanceToNow(galgame.created)}</Chip>
            </div>

            <KunCardStats patch={galgame} />

            <div className="flex flex-wrap gap-2">
              {galgame.type.map((type) => (
                <Chip
                  key={type}
                  size="sm"
                  color="primary"
                  variant="flat"
                  className="text-xs"
                >
                  {SUPPORTED_TYPE_MAP[type]}
                </Chip>
              ))}
            </div>
          </div>
        </div>
      </CardBody>
    </Card>
  )
}

// apps/web/app/components/galgame/Card.vue
<script setup lang="ts">
import { GALGAME_AGE_LIMIT_MAP } from '~/constants/galgame'

interface Props {
  patch: GalgameCard
}

const props = defineProps<Props>()

const galgameName = computed(() => getPreferredLanguageText(props.patch.name))

const imageLoaded = ref(false)

const bannerSrc = computed(() =>
  props.patch.banner
    ? props.patch.banner.replace(/\.avif$/, '-mini.avif')
    : '/kungalgame-trans.webp'
)
</script>

<template>
  <KunCard
    is-pressable
    :href="`/patch/${props.patch.id}/introduction`"
    class-name="w-full border-default-100 dark:border-default-200 border"
    content-class="gap-0 p-0"
  >
    <div
      class="relative mx-auto w-full overflow-hidden rounded-t-lg text-center opacity-90"
    >
      <div
        :class="
          cn(
            'bg-default-100 absolute inset-0 animate-pulse',
            imageLoaded ? 'opacity-0' : 'opacity-90',
            'transition-opacity duration-300'
          )
        "
        style="aspect-ratio: 16 / 9"
      />
      <KunImage
        :alt="galgameName"
        :src="bannerSrc"
        :class="
          cn(
            'size-full object-cover transition-all duration-300',
            imageLoaded ? 'scale-100 opacity-90' : 'scale-105 opacity-0'
          )
        "
        style="aspect-ratio: 16 / 9"
        @load="imageLoaded = true"
      />

      <div class="bg-background absolute top-2 left-2 z-10 rounded-full">
        <KunBadge
          :color="props.patch.content_limit === 'sfw' ? 'success' : 'danger'"
          variant="flat"
        >
          {{ GALGAME_AGE_LIMIT_MAP[props.patch.content_limit] }}
        </KunBadge>
      </div>
    </div>

    <div class="flex flex-col justify-between space-y-2 p-3">
      <h2
        class="text-medium hover:text-primary-500 space-x-2 font-semibold transition-colors line-clamp-2 sm:text-lg"
      >
        <span>{{ galgameName }}</span>
        <span class="text-default-500 text-xs font-normal">
          {{ formatDistanceToNow(props.patch.created) }}
        </span>
      </h2>
      <KunCardStats :patch="props.patch" />
    </div>

    <div class="px-3 pt-0 pb-3">
      <KunPatchAttribute
        :types="props.patch.type"
        :languages="props.patch.language"
        :platforms="props.patch.platform"
        size="sm"
      />
    </div>
  </KunCard>
</template>
